# Generated by Django 3.2.6 on 2021-08-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0013_receipt'),
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='authtoken.token')),
            ],
        ),
        migrations.CreateModel(
            name='NodeWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='node.node')),
            ],
        ),
        migrations.CreateModel(
            name='NodePrintJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('created', 'Created'), ('queued', 'Queued'), ('acked', 'Acknowledged by node'), ('printed', 'Printed'), ('discarded', 'Discarded'), ('aborted', 'Aborted')], default='created', max_length=64)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='node.node')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='pos.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='NodePrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_type', models.CharField(choices=[('epson', 'Generic Epson printer')], max_length=64)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printers', to='node.node')),
            ],
        ),
    ]
