# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_category_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='card',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'CASH'), (1, 'CREW'), (2, 'CARD'), (3, 'VIPPS'), (4, 'MCASH'), (5, 'MOBILEPAY'), (6, 'IZETTLE'), (7, 'UNDO')], db_index=True, default=0),
        ),
    ]
