# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-29 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_itemingredient_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='is_cashier',
            field=models.BooleanField(default=False),
        ),
    ]
