# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20160920_2108'),
        ('pos', '0002_crewsession'),
    ]

    operations = [
    ]
