# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-02 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20170902_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier', to='pos.User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasing_user', to='pos.User'),
        ),
    ]
