# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_merge_20160926_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cashier', to='pos.Crew'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasing_crew', to='pos.Crew'),
        ),
    ]
