# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20160429_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_in_the_kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'OPEN'), (1, 'IN_PROGRESS'), (2, 'DELIVERED')], default=0),
        ),
    ]
