# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20160926_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasing_crew', to='pos.Crew'),
        ),
    ]
