# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0006_auto_20160926_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='leader',
        ),
        migrations.AddField(
            model_name='shift',
            name='authenticated_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
