# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-25 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20180925_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_crew',
            field=models.BooleanField(default=False),
        ),
    ]
