# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20160702_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'CASH'), (1, 'CREW'), (2, 'CARD'), (3, 'VIPPS'), (4, 'MCASH'), (5, 'MOBILEPAY'), (6, 'IZETTLE')], default=0),
        ),
    ]
