# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20160927_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='crew',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='pos.Crew'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'CASH'), (1, 'CREW'), (2, 'CARD'), (3, 'VIPPS'), (4, 'MCASH'), (5, 'MOBILEPAY'), (6, 'IZETTLE'), (7, 'UNDO')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'CASH'), (1, 'CREW'), (2, 'CARD'), (3, 'VIPPS'), (4, 'MCASH'), (5, 'MOBILEPAY'), (6, 'IZETTLE'), (7, 'UNDO')], default=0),
        ),
    ]
