# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_merge_20160914_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='default_ingredients',
            field=models.ManyToManyField(blank=True, to='pos.Ingredient'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
