# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_auto_20160916_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.SmallIntegerField(),
        ),
    ]
