# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-10-03 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_creditupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditupdate',
            name='geekevents_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
