# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_auto_20160916_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
