version: "3.5"

x-env: &env
  env_file:
    - config/env/base.env
    - config/env/generated.env
    - config/env/local.env

services:
  server:
    <<: *env
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=p0sx.settings.env
    image: p0sx-server
    command: devserver
    volumes:
      - ".:/code"
      - "./media:/media"
      - "./logs:/logs"
      - "pip-cache:/tmp/pip"
      - "ipython-data-local:/root/.ipython/profile_default"   # persist ipython data, including ipython history
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8000:8000"
    restart: always

  postgres:
    image: postgres:12
    <<: *env
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Cache and task broker
  redis:
    image: redis
    <<: *env
    volumes:
      - "redis_data:/var/lib/redis"
    restart: always


volumes:
  pip-cache:
    driver: local
  ipython-data-local:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local
