# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-02 10:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0003_crew_is_cashier'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Crew',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='crewsession',
            name='crew',
        ),
        migrations.RemoveField(
            model_name='crewsession',
            name='user',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='crew',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='crew',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasing_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discount',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'CASH'), (1, 'CREDIT'), (2, 'CARD'), (3, 'VIPPS'), (4, 'MCASH'), (5, 'MOBILEPAY'), (6, 'IZETTLE'), (7, 'UNDO')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'CASH'), (1, 'CREDIT'), (2, 'CARD'), (3, 'VIPPS'), (4, 'MCASH'), (5, 'MOBILEPAY'), (6, 'IZETTLE'), (7, 'UNDO')], db_index=True, default=0),
        ),
        migrations.DeleteModel(
            name='CrewSession',
        ),
        migrations.AddField(
            model_name='usersession',
            name='django_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.User'),
        ),
    ]
