# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-05 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_auto_20191003_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumUpAPIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=512)),
                ('client_secret', models.CharField(max_length=512)),
                ('access_code_state', models.UUIDField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=256, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=256, null=True)),
                ('refresh_token_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SumUpTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=32)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='pos.SumUpAPIKey')),
            ],
        ),
        migrations.CreateModel(
            name='SumUpTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handled', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=256)),
                ('transaction_code', models.CharField(max_length=64)),
                ('user', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('timestamp', models.DateTimeField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pos.SumUpAPIKey')),
            ],
        ),
    ]
