# Generated by Django 3.2.6 on 2021-08-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_sumupapikey_sumupterminal_sumuptransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
