# Generated by Django 3.2.6 on 2021-08-22 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_sumupapikey_sumupterminal_sumuptransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumUpCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.SmallIntegerField(choices=[(0, 'CREATED'), (1, 'PROCESSING'), (2, 'SUCCESS'), (3, 'FAILED'), (4, 'COMPLETE')], default=0)),
                ('transaction_id', models.CharField(max_length=64, null=True)),
                ('transaction_comment', models.CharField(max_length=256, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.user')),
            ],
        ),
    ]
