# Generated by Django 3.2.6 on 2021-08-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_sumupcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumupcard',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumupcard',
            name='transaction_comment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sumupcard',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
