# Generated by Django 3.2.6 on 2021-10-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_auto_20210823_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeekeventsToken',
            fields=[
                ('token', models.CharField(max_length=255)),
                ('ge_user_id', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pos.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='geekeventstoken',
            constraint=models.UniqueConstraint(fields=('ge_user_id',), name='GeekEvents user ID must be unique'),
        ),
    ]
