# Generated by Django 3.2.6 on 2021-10-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_auto_20211009_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
