# Generated by Django 3.2.6 on 2021-08-23 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_auto_20210823_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumupcard',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
