# Generated by Django 3.2.6 on 2021-10-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_auto_20210907_0919'),
        ('pos', '0015_orderline_message'),
    ]

    operations = [
    ]
