# Generated by Django 3.2.6 on 2021-08-23 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0016_alter_sumupcard_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumupcard',
            name='authorized_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
