# Generated by Django 3.2.6 on 2021-10-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_merge_0014_auto_20210907_0919_0015_orderline_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='orderline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log', to='pos.orderline'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
