# Generated by Django 3.2.6 on 2021-10-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_auto_20211010_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'CASH'), (1, 'CREDIT'), (2, 'CARD'), (3, 'VIPPS'), (4, 'PREPAID'), (5, 'MOBILEPAY'), (6, 'IZETTLE'), (7, 'UNDO')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'CASH'), (1, 'CREDIT'), (2, 'CARD'), (3, 'VIPPS'), (4, 'PREPAID'), (5, 'MOBILEPAY'), (6, 'IZETTLE'), (7, 'UNDO')], db_index=True, default=0),
        ),
    ]
