# Generated by Django 3.2.6 on 2021-08-23 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_sumupcard_authorized_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditupdate',
            name='updated_by_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user', to='pos.user'),
        ),
    ]
