# Generated by Django 3.2.6 on 2021-08-23 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_alter_creditupdate_updated_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumupcard',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='sumupcard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
