# Generated by Django 3.2.25 on 2025-10-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_state',
            field=models.SmallIntegerField(choices=[(0, 'PAID'), (1, 'PENDING'), (2, 'FAILED'), (3, 'CANCELLED')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'CASH'), (1, 'CREDIT'), (2, 'CARD'), (3, 'VIPPS'), (4, 'PREPAID'), (7, 'UNDO')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'CASH'), (1, 'CREDIT'), (2, 'CARD'), (3, 'VIPPS'), (4, 'PREPAID'), (7, 'UNDO')], db_index=True, default=0),
        ),
    ]
