# Generated by Django 3.2.6 on 2021-08-23 03:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_auto_20210823_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sumupcard',
            name='id',
        ),
        migrations.AlterField(
            model_name='sumupcard',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
