# Generated by Django 3.2.6 on 2021-08-23 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_auto_20210823_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sumupcard',
            old_name='uuid',
            new_name='id',
        ),
    ]
