# Generated by Django 3.2.25 on 2025-10-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_sumupreader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sumupcard',
            name='authorized_user',
        ),
        migrations.RemoveField(
            model_name='sumupcard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sumuponline',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sumupterminal',
            name='key',
        ),
        migrations.RemoveField(
            model_name='sumuptransaction',
            name='key',
        ),
        migrations.DeleteModel(
            name='SumUpAPIKey',
        ),
        migrations.DeleteModel(
            name='SumUpCard',
        ),
        migrations.DeleteModel(
            name='SumUpOnline',
        ),
        migrations.DeleteModel(
            name='SumUpTerminal',
        ),
        migrations.DeleteModel(
            name='SumUpTransaction',
        ),
    ]
