# Generated by Django 3.2.25 on 2025-10-05 22:18

from django.db import migrations, models
import django.db.models.deletion
import pos.models.stock


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_auto_20251005_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumupTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_state', models.SmallIntegerField(choices=[(0, 'PAID'), (1, 'PENDING'), (2, 'FAILED'), (3, 'CANCELLED')], default=pos.models.stock.PaymentState['Pending'])),
                ('payment_reference', models.CharField(blank=True, max_length=256, null=True)),
                ('authenticated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_authorized_user', to='pos.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_user', to='pos.user')),
            ],
        ),
    ]
