# Generated by Django 3.2.25 on 2025-10-06 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0024_sumuptransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumuptransaction',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sumuptransaction',
            name='authenticated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_authorized_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
